"""agrego tabla permisos MtM

Revision ID: 0eb3d410088c
Revises: 733de5b910bd
Create Date: 2021-03-30 18:35:45.482570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb3d410088c'
down_revision = '733de5b910bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas_pendientes')
    op.drop_table('tareas_acciones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas_acciones',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_modified', sa.DATETIME(), nullable=True),
    sa.Column('id_tarea', sa.INTEGER(), nullable=False),
    sa.Column('id_accion', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_accion'], ['acciones.id'], ),
    sa.ForeignKeyConstraint(['id_tarea'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_tarea', 'id_accion')
    )
    op.create_table('tareas_pendientes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_modified', sa.DATETIME(), nullable=True),
    sa.Column('id_tarea', sa.INTEGER(), nullable=False),
    sa.Column('id_recupero', sa.INTEGER(), nullable=False),
    sa.Column('fe_vencimiento', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_recupero'], ['recuperos.id'], ),
    sa.ForeignKeyConstraint(['id_tarea'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
