"""tabla user corregida

Revision ID: 46447b16ba37
Revises: e4c9e7af15f9
Create Date: 2021-03-28 00:38:32.762965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46447b16ba37'
down_revision = 'e4c9e7af15f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('apellido', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('fe_ultima_contrasenia', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('nombre', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'nombre')
    op.drop_column('users', 'fe_ultima_contrasenia')
    op.drop_column('users', 'apellido')
    # ### end Alembic commands ###
