"""actualizacion del modeloPrimerabase

Revision ID: 733de5b910bd
Revises: 
Create Date: 2021-03-29 15:12:08.800019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733de5b910bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('vencimiento', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=22), nullable=True),
    sa.Column('about_me', sa.String(length=280), nullable=True),
    sa.Column('status', sa.String(length=2), nullable=False),
    sa.Column('fe_ultima_contrasenia', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('acciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('estado_recupero', sa.Integer(), nullable=True),
    sa.Column('id_tarea_siguiente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_tarea_siguiente'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recuperos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('rama', sa.Integer(), nullable=True),
    sa.Column('siniestro', sa.Integer(), nullable=True),
    sa.Column('fe_ocurrencia', sa.DateTime(), nullable=True),
    sa.Column('fe_denuncia', sa.DateTime(), nullable=True),
    sa.Column('fe_pago', sa.DateTime(), nullable=True),
    sa.Column('importe_pagado', sa.Float(), nullable=True),
    sa.Column('compania', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('desc_sinestro', sa.Text(), nullable=True),
    sa.Column('tercero', sa.String(length=50), nullable=True),
    sa.Column('tel_tercero', sa.String(length=50), nullable=True),
    sa.Column('mail_tercero', sa.String(length=50), nullable=True),
    sa.Column('asegurado', sa.String(length=50), nullable=True),
    sa.Column('monto_franquicia', sa.Float(), nullable=True),
    sa.Column('responsabilidad', sa.Integer(), nullable=True),
    sa.Column('usuario_responsable', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_responsable'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas_acciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.Column('id_accion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_accion'], ['acciones.id'], ),
    sa.ForeignKeyConstraint(['id_tarea'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_tarea', 'id_accion')
    )
    op.create_table('tareas_pendientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.Column('id_recupero', sa.Integer(), nullable=False),
    sa.Column('fe_vencimiento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_recupero'], ['recuperos.id'], ),
    sa.ForeignKeyConstraint(['id_tarea'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas_pendientes')
    op.drop_table('tareas_acciones')
    op.drop_table('recuperos')
    op.drop_table('image')
    op.drop_table('acciones')
    op.drop_table('users')
    op.drop_table('tareas')
    # ### end Alembic commands ###
