"""correccion

Revision ID: eda8b009e0b6
Revises: 
Create Date: 2021-04-15 20:58:18.710240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda8b009e0b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('correos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equiposusuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('equipo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo')
    )
    op.create_table('estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('desc_estado', sa.String(), nullable=False),
    sa.Column('estado_tabla', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfilesusuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('puesto', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puesto')
    )
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('formulario', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsabilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('desc_responsabilidad', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('vencimiento', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=22), nullable=True),
    sa.Column('about_me', sa.String(length=280), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('fe_ultima_contrasenia', sa.DateTime(), nullable=True),
    sa.Column('puesto', sa.Integer(), nullable=False),
    sa.Column('equipo', sa.Integer(), nullable=False),
    sa.Column('dependencia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('acciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('estado_recupero', sa.Integer(), nullable=True),
    sa.Column('id_tarea_siguiente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_tarea_siguiente'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correoselectronicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('correo', sa.String(length=50), nullable=False),
    sa.Column('id_compania', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_compania'], ['companias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recuperos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('rama', sa.Integer(), nullable=True),
    sa.Column('siniestro', sa.Integer(), nullable=True),
    sa.Column('fe_ocurrencia', sa.DateTime(), nullable=True),
    sa.Column('fe_denuncia', sa.DateTime(), nullable=True),
    sa.Column('fe_pago', sa.DateTime(), nullable=True),
    sa.Column('importe_pagado', sa.Float(), nullable=True),
    sa.Column('compania', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('desc_siniestro', sa.Text(), nullable=True),
    sa.Column('tercero', sa.String(length=50), nullable=True),
    sa.Column('tel_tercero', sa.String(length=50), nullable=True),
    sa.Column('mail_tercero', sa.String(length=50), nullable=True),
    sa.Column('asegurado', sa.String(length=50), nullable=True),
    sa.Column('monto_franquicia', sa.Float(), nullable=True),
    sa.Column('responsabilidad', sa.Integer(), nullable=True),
    sa.Column('usuario_responsable', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_responsable'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuariospermisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_usuario', 'id_permiso')
    )
    op.create_table('tareasacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.Column('id_accion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_accion'], ['acciones.id'], ),
    sa.ForeignKeyConstraint(['id_tarea'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_tarea', 'id_accion')
    )
    op.create_table('tareaspendientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.Column('id_recupero', sa.Integer(), nullable=False),
    sa.Column('fe_vencimiento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_recupero'], ['recuperos.id'], ),
    sa.ForeignKeyConstraint(['id_tarea'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareaspendientes')
    op.drop_table('tareasacciones')
    op.drop_table('usuariospermisos')
    op.drop_table('recuperos')
    op.drop_table('image')
    op.drop_table('correoselectronicos')
    op.drop_table('acciones')
    op.drop_table('users')
    op.drop_table('tareas')
    op.drop_table('responsabilidades')
    op.drop_table('permisos')
    op.drop_table('perfilesusuarios')
    op.drop_table('estados')
    op.drop_table('equiposusuarios')
    op.drop_table('companias')
    # ### end Alembic commands ###
